import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App.jsx'
import './styles/app.css'
import './styles/preloader.css'
import './styles/footer.css'
import './styles/festivals.css'
import './styles/gallery.css'
import './styles/visit.css'
createRoot(document.getElementById('root')).render(<BrowserRouter><App /></BrowserRouter>)
